#!/usr/bin/env python
#-*- coding:utf-8 -*-
"""
test
"""
import sys, os

def main():
    file = sys.argv[1]
    os.system('rst2html %s > temp/s.html; o temp/s.html' % file)

if __name__ == "__main__":
    main()


